name: formatter

on:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:    
      contents: write
    strategy:
      matrix:
        python-version: [3.10.12]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format libxml2-utils
          pip install --upgrade pip
          pip install autoflake autopep8 isort black
          rustup update
          rustup component add rustfmt

      # Python Formatting
      - name: Run autoflake
        run: |
          find . -type f -name "*.py" -exec autoflake --in-place --remove-unused-variables --remove-all-unused-imports {} \;

      - name: Run isort
        run: |
          find . -type f -name "*.py" -exec isort {} \;

      - name: Run black
        run: |
          black .

      # XML / URDF Formatting
      - name: Run xmllint
        run: |
          find . -type f \( -name "*.xml" -or -name "*.gazebo" -or -name "*.xacro" -or -name "*.urdf" -or -name "*.sdf" \) -exec xmllint --format -o {} {} \;

      # Auto commit if any changes
      - name: Auto commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Apply formatting to PR files"
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com